sudo: false
language: python
python:
  - "2.7"
jobs:
  include:
    - name: "Lint"
      install:
        - pip install -r requirements.txt
        - pip install flake8==3.5.0 pylint==1.9.3 tzlocal pillow
      script:
        - flake8 esphomeyaml
        - pylint esphomeyaml
    - name: "Test 1"
      install:
        - pip install -e .
        - pip install tzlocal pillow
      script:
        - esphomeyaml tests/test1.yaml compile
    - name: "Test 2"
      install:
        - pip install -e .
        - pip install tzlocal pillow
      script:
        - esphomeyaml tests/test2.yaml compile
